### ISSUE TITLE
the trait bound `CangJieTokenizer: From<CangJieTokenizer>` is not satisfied required because of the requirements on the impl of `From<CangJieTokenizer>` for `TextAnalyzer`

### ISSUE THREAD

**Issue by carmel** [DCjanus/cang-jie#22]
![image](https://user-images.githubusercontent.com/36031579/126841289-b5628b29-14a6-41d3-810d-fdb4b5787dad.png)

```toml
[dependencies]
byteorder = "1.4.3"
log = "0.4.14"
log4rs = "1.0.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
# serde_yaml = "0.8.17"
clap = "3.0.0-beta.2"
tantivy = "0.15.3"
jieba-rs = "0.6.5"
cang-jie = "0.11.1"
```

**Comment by DCjanus** [comment]
upgrade `cang-jie` to `0.12.0` should fix this issue.

**Comment by carmel** [comment]
谢谢，处理的很快。不过还是一样的错误

```toml
[dependencies]
byteorder = "1.4.3"
log = "0.4.14"
log4rs = "1.0.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
# serde_yaml = "0.8.17"
clap = "3.0.0-beta.2"
tantivy = "0.15.3"
jieba-rs = "0.6.5"
cang-jie = "0.12.0"
```
